import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/Header'
import About from '../components/home/about'
import Portfolio from '../components/home/portfolio'
import Services from '../components/home/services'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <About />
      <Services/>
      <Portfolio />
    </div>
  )
}
